version: '3.8'

services:

  wsgiserver:
    build: .
    # image: kenun/simple-cd:latest
    container_name: simple-cd
    entrypoint: docker/backend/web.sh
    # command: ls docker/backend
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - back

  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     # - /root/.docker/config.json:/config.json
  #   command: --interval 30 simple-cd

networks:
    back:
