version: '3.8'

services:
  wsgiserver:
    image: kenun/simple-cd:latest
    build: .
    container_name: simple-cd
    entrypoint: docker/backend/web.sh
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - back
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 simple-cd

networks:
    back:
