[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line-lenght = 120

[tool.pyright]
pythonVersion = "3.11"
pythonPlatform = "Linux"
reportGeneralTypeIssues = false
