name: GitHub Actions Test
run-name: ${{ github.actor }} is testing out GutGub Actions
on: [pull_request]
jobs:
  run_unittests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd .
          echo "SECRET_KEY = 'django-insecure-dummy-secret'" > .env
          python3 manage.py test .
